In [2]:
# Import PyTorch
import torch

# Check for Apple Silicon GPU
torch.backends.mps.is_available() # Note this will print false if you're not running on a Mac

True

In [5]:
# Set device type
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available

# Print device type
print(f"Device: {device}")

Device: mps


In [7]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='mps:0')

In [6]:
torch.manual_seed(1234)

A = torch.rand(2, 3)
A

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])