# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Set device type
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available

# Create random tensor
A = torch.rand(7, 7)
A

tensor([[0.3325, 0.9977, 0.7465, 0.5845, 0.3150, 0.2595, 0.9774],
        [0.9548, 0.8833, 0.3900, 0.2931, 0.1031, 0.8218, 0.6336],
        [0.4656, 0.0260, 0.1821, 0.6954, 0.4364, 0.9818, 0.9087],
        [0.5087, 0.2466, 0.8557, 0.5786, 0.6368, 0.2282, 0.3326],
        [0.9226, 0.7913, 0.0800, 0.9177, 0.8556, 0.2051, 0.7531],
        [0.0116, 0.2716, 0.4576, 0.3471, 0.0193, 0.8785, 0.9564],
        [0.3163, 0.6515, 0.5487, 0.4432, 0.1836, 0.5175, 0.5103]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
B = torch.rand(1, 7)
B


# Perform matrix multiplication 
A @ B.T

tensor([[1.4292],
        [1.7396],
        [1.8786],
        [1.2803],
        [1.7506],
        [1.4089],
        [1.2213]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
RANDOM_SEED = 0
torch.random.manual_seed(seed=RANDOM_SEED) 


# Create two random tensors
TENSOR_7_by_7 = torch.rand(7, 7)
B = torch.rand(1, 7)


# Matrix multiply tensors
TENSOR_7_by_7 @ B.T

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
RANDOM_SEED = 1234
torch.mps.manual_seed(RANDOM_SEED)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
# Set random seed
RANDOM_SEED = 1234
torch.manual_seed(RANDOM_SEED)

# Check for access to GPU
torch.backends.mps.is_available()
device = "mps" if torch.backends.mps.is_available() else "cpu"
print(device)

# Create two random tensors on GPU
A = torch.rand(2, 3).to(device)
B = torch.rand(2, 3).to(device)

A, B


mps


/Users/hientrinh/Desktop/machine-learning-workspace/zero-to-mastery-learn-pytorch/.venv/lib/python3.12/site-packages/torch/_tensor_str.py:138: UserWarning: MPS: nonzero op is supported natively starting from macOS 13.0. Falling back on CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/operations/Indexing.mm:335.)
  nonzero_finite_vals = torch.masked_select(


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='mps:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='mps:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [11]:
# Perform matmul on tensor_A and tensor_B
C = A @ B.T


### 8. Find the maximum and minimum values of the output of 7.

In [13]:
# Find max
print(C.max())

# Find min
print(C.min())

tensor(0.5617, device='mps:0')
tensor(0.3647, device='mps:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [14]:
# Find arg max
print(C.argmax())

# Find arg min
print(C.argmin())


tensor(3, device='mps:0')
tensor(0, device='mps:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [15]:
# Set seed
RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)


# Create random tensor
A = torch.rand(1, 1, 1, 10)

# Remove single dimensions
B = A[0, 0, 0, :]


# Print out tensors and their shapes
A, B

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]))